### ISSUE TITLE
Dev plan

### ISSUE THREAD

**Issue by yuzhichang** [vectorengine/vectorsql#1]
What's the completed features and development plan?

**Comment by BohuTANG** [comment]
The short-term plans are:
1. supports ClickHouse datas insert, memory and merge-tree storage
2. more functions, such as aggregations, table valued functions
3. performance tuning
4. more tests

Long-term plans:
1. supports join
2. distributed query engine with priority
3. more storages
4. more ClickHouse-like

**Comment by BohuTANG** [comment]
@yuzhichang 
Hello, all the development and release plan has moved to the github projects:
https://github.com/vectorengine/vectorsql/projects
