### ISSUE TITLE
Why not using go module to manage dependencies?

### ISSUE THREAD

**Issue by choleraehyq** [vectorengine/vectorsql#34]
Currently we need to set vectorsql as GOPATH, which is quite weird.

**Comment by BohuTANG** [comment]
Hello,

Aha, We don't like the go module style, vendor maybe a tricky job in a gopher room but it works well.
VectorSQL as a DBMS, when you git clone the code to local, everything works, it's no bothers on Build/Test and others what you want.

**Comment by choleraehyq** [comment]
Okay, thanks for answering.
