### ISSUE TITLE
src\base\xlog\xlog.go:52:12: undefined: syslog.New

### ISSUE THREAD

**Issue by tlightsky** [vectorengine/vectorsql#39]
```go
$ go build -v -o bin/vectorsql-server src/cmd/server.go
base/xlog
# base/xlog
src\base\xlog\xlog.go:52:12: undefined: syslog.New
src\base\xlog\xlog.go:52:23: undefined: syslog.LOG_DEBUG
```

**Comment by BohuTANG** [comment]
Thanks for the report, I will try and fix it.

**Comment by BohuTANG** [comment]
Fixed https://github.com/vectorengine/vectorsql/commit/d1d87ecf9a2df0984cffcb55f0f0665b95da9f56

**Comment by tlightsky** [comment]
cool, `confirmed`, i can run it now
the makefile seems not working under windows, 
but i can build it manually,
so i guess it's fine now, 
good job
